---
- name: Install nginx
  become: True
  apt:
    name: nginx
    state: present
    update_cache: True
    cache_valid_time: 1800

- name: Install nginx SPENGO module
  become: True
  apt:
    name: libnginx-mod-http-auth-spnego
    state: present
    update_cache: True
    cache_valid_time: 1800

- name: Enable nginx SPENGO module
  become: True
  file:
    src: /usr/share/nginx/modules-available/mod-http-auth-spnego.conf
    dest: /etc/nginx/modules-enabled/50-mod-http-auth-spnego.conf
    state: link

- name: Create certificate directory
  become: True
  file:
    path: "/etc/nginx/certs/{{ nginx_fqdn }}"
    state: directory

- name: Create LE directory
  become: True
  file:
    path: "{{ nginx_ledir }}"
    state: directory

- name: Create base vhost drop-in directory
  become: True
  file:
    path: /etc/nginx/base.d
    state: directory

- name: Create custom vhost drop-in directory
  become: True
  with_items: "{{ nginx_extra_hosts }}"
  file:
    path: "/etc/nginx/{{ item.name }}.d"
    state: directory

- name: Check if certificates exist
  stat:
    path: "{{ nginx_fullchain_path }}"
  register: certstat

- name: Copy snakeoil certificate
  become: True
  copy:
    src: snakeoil.pem
    dest: "{{ nginx_fullchain_path }}"
  when: not certstat.stat.exists

- name: Copy snakeoil certificate key
  become: True
  copy:
    src: snakeoil.key
    dest: "{{ nginx_key_path }}"
  when: not certstat.stat.exists

- name: Disable nginx default vhost
  become: True
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Copy ip range config
  become: True
  template:
    src: ranges.conf.j2
    dest: /etc/nginx/conf.d/ranges.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Copy new base vhost
  become: True
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/base.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Copy custom vhost
  become: True
  with_items: "{{ nginx_extra_hosts }}"
  template:
    src: nginx-extrahost.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ item.name }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Enable nginx
  become: True
  service:
    name: nginx
    enabled: yes

- meta: flush_handlers
